# Generated by Django 3.0.6 on 2020-06-03 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secureX_site', '0002_auto_20200603_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
