# Generated by Django 3.0.6 on 2020-06-03 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secureX_site', '0003_services_image'),
    ]

    operations = [
        
        migrations.RenameModel(
            old_name='Service',
            new_name='Service',
        ),
        migrations.RenameModel(
            old_name='RequestService',
            new_name='RequestService',
        ),
        
    ]
