# Generated by Django 3.0.6 on 2020-06-03 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('secureX_site', '0004_auto_20200604_0011'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('information', models.TextField()),
                ('contact', models.CharField(max_length=20)),
                ('cost', models.CharField(max_length=20)),
                ('image', models.ImageField(default='default.jpg', upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='RequestService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=42)),
                ('lname', models.CharField(max_length=42)),
                ('email', models.EmailField(max_length=75)),
                ('contact', models.CharField(max_length=20)),
                ('purpose', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secureX_site.Service')),
            ],
        ),
    ]
