# Generated by Django 3.0.6 on 2020-06-03 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secureX_site', '0005_requestservice_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestservice',
            old_name='contact',
            new_name='contactnumber',
        ),
    ]
