# Generated by Django 3.0.6 on 2020-06-08 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('secureX_site', '0006_auto_20200604_0204'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branchname', models.CharField(max_length=75)),
                ('building', models.CharField(max_length=75)),
                ('street', models.CharField(max_length=75)),
                ('city', models.CharField(max_length=75)),
                ('state', models.CharField(max_length=75)),
                ('email', models.EmailField(max_length=75)),
                ('contactnumber', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='OpenJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobname', models.CharField(max_length=42)),
                ('payrange', models.CharField(max_length=75)),
                ('jobtype', models.CharField(max_length=42)),
                ('location', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=75)),
                ('lname', models.CharField(max_length=75)),
                ('email', models.EmailField(max_length=75)),
                ('gender', models.CharField(max_length=75)),
                ('dateofbirth', models.DateField()),
                ('address', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=75)),
                ('state', models.CharField(max_length=75)),
                ('pincode', models.IntegerField()),
                ('contactnumber', models.CharField(max_length=20)),
                ('expectedsalary', models.CharField(max_length=75)),
                ('education', models.CharField(max_length=75)),
                ('workexperience', models.CharField(max_length=75)),
                ('status', models.CharField(max_length=75)),
                ('jobpost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secureX_site.OpenJob')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
