# Generated by Django 3.0.6 on 2020-06-08 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secureX_site', '0007_branchlocation_jobapplication_openjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(default='Pending', max_length=75),
        ),
    ]
