# Generated by Django 3.0.6 on 2020-06-15 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secureX_site', '0009_course_order_orderitem_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pincode',
            field=models.IntegerField(null=True),
        ),
    ]
